let paragraphs = [
	"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit ex nesciunt fugit, tempora cupiditate minima?",
	"The quick brown fox jumps over the lazy dog and tragically dies, to make a point about the futility of the American Dream.",
	"No kidding, Lorenzo called off his trip to visit Mexico City just because they told him the conquistadors were extinct.",
	"A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.",
	"It also encouraged vivisection-a practice common with Descartes himself.",
	"He had tried to teach her to play the piano many times through the years, but she always became bored within a week or so of practice and gave up.",
	"The purpose of this apartment was to give her a place to practice being human.",
	"Rhyn rested back on the boulder and closed his eyes to the rhythmic sounds of waves and Gabriel trying to kill the practice dummy.",
	"Second are the inefficiencies in the human processes-that is, the techniques by which we practice agriculture.",
	"In the rural areas, there was less concern with traffic, although an occasional farm dog forced him to practice his sprints.",
	"Martha, free to indulge, surprised me by drinking more than her share, an uncommon practice on her part.",
	"Maybe she did write it years earlier and it really is her practice work, he offered.",
	"A'Ran left the command center for the practice fields, the area behind the dwelling where his men fought.",
	"In spite of the time lapse between practice sessions, she did well enough to win his praise.",
	"Your ma told me you had baseball practice and nothing unusual happened.",
	"It seems to me when you practice letters, you print uppercase letters first, don't you?",
];
